apiVersion: v1
kind: Namespace
metadata:
  name: default
  annotations:
    kubearmor-file-posture: block
    kubearmor-process-posture: block
    kubearmor-network-posture: block
    kubearmor-capabilities-posture: block
